name: Testing

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - uses: actions/checkout@v2
      - run: godot -d -s --path $PWD addons/gut/gut_cmdln.gd
